fix: Fix 'Cannot Clean Up' error #4

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -498,25 +498,31 @@ jobs:
                 command: |
                     # Get current workflow ID
                     export CurrentWorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}"
-                    
                     echo "Current Workflow Id: ${CurrentWorkflowID}"
+
+                    # if ${CIRCLE_WORKFLOW_ID:0:7} is empty, then raise error
+                    if [[ ! -z "${CIRCLE_WORKFLOW_ID:0:7}" ]]
+                    then
+                        echo 'ERROR: CANNOT CLEAN UP'
+                        exit 1;
+                    fi
 
                     # Get old workflow ID
                     export OldWorkflowIDs=$(aws cloudformation \
                     list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
                     --no-paginate --output text)
 
-                    echo "Old Workflow Id: ${OldWorkflowIDs}"
+                    echo "Old Workflow Ids: ${OldWorkflowIDs}"
 
                     # For each WorkFlow ID,
                     # If Old Workflow ID is NOT Current Workflow ID, then delete
-                    for $WorkFlowID in "${ListWorkFlowIDs[@]}"; do
+                    for $WorkFlowID in "${OldWorkflowIDs[@]}"; do
                         if [[ "${CurrentWorkflowID}" != "${WorkFlowID}" ]] 
                         then
                             echo 'CLEANING UP OLD STACK'
-                            aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-                            aws cloudformation delete-stack --stack-name "udapeople-${OldWorkflowID}-backend"
-                            aws cloudformation delete-stack --stack-name "udapeople-${OldWorkflowID}-frontend"
+                            aws s3 rm "s3://${OldWorkflowID}" --recursive
+                            aws cloudformation delete-stack --stack-name "${OldWorkflowID}-backend"
+                            aws cloudformation delete-stack --stack-name "${OldWorkflowID}-frontend"
                         fi
                     done
 
